<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      DB::table('countries')->insert(
        array(
            array('id' => '1','sevdesk_id' => '4','code' => 'af','name' => 'Afghanistan','name_en' => 'Afghanistan','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '2','sevdesk_id' => '1383','code' => 'eg','name' => 'Ägypten','name_en' => 'Egypt','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '3','sevdesk_id' => '1468','code' => 'ax','name' => 'Åland','name_en' => 'Åland Islands','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '4','sevdesk_id' => '1347','code' => 'al','name' => 'Albanien','name_en' => 'Albania','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '5','sevdesk_id' => '1458','code' => 'dz','name' => 'Algerien','name_en' => 'Algeria','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '6','sevdesk_id' => '1469','code' => 'as','name' => 'Amerikanisch-Samoa','name_en' => 'American Samoa','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '7','sevdesk_id' => '1559','code' => 'vi','name' => 'Amerikanische Jungferninseln','name_en' => 'United States Virgin Islands','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '8','sevdesk_id' => '1418','code' => 'ad','name' => 'Andorra','name_en' => 'Andorra','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '9','sevdesk_id' => '1466','code' => 'ao','name' => 'Angola','name_en' => 'Angola','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '10','sevdesk_id' => '1467','code' => 'ai','name' => 'Anguilla','name_en' => 'Anguilla','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '11','sevdesk_id' => '1470','code' => 'aq','name' => 'Antarktis','name_en' => 'Antarctica','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '12','sevdesk_id' => '1449','code' => 'ag','name' => 'Antigua und Barbuda','name_en' => 'Antigua and Barbuda','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '13','sevdesk_id' => '1503','code' => 'gq','name' => 'Äquatorialguinea','name_en' => 'Equatorial Guinea','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '14','sevdesk_id' => '5','code' => 'ar','name' => 'Argentinien','name_en' => 'Argentina','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '15','sevdesk_id' => '1348','code' => 'am','name' => 'Armenien','name_en' => 'Armenia','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '16','sevdesk_id' => '1465','code' => 'aw','name' => 'Aruba','name_en' => 'Aruba','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '17','sevdesk_id' => '33','code' => 'az','name' => 'Aserbaidschan','name_en' => 'Azerbaijan','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '18','sevdesk_id' => '1399','code' => 'et','name' => 'Äthiopien','name_en' => 'Ethiopia','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '19','sevdesk_id' => '38','code' => 'au','name' => 'Australien','name_en' => 'Australia','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '20','sevdesk_id' => '1426','code' => 'bs','name' => 'Bahamas','name_en' => 'Bahamas','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '21','sevdesk_id' => '1427','code' => 'bh','name' => 'Bahrain','name_en' => 'Bahrain','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '22','sevdesk_id' => '1440','code' => 'bd','name' => 'Bangladesch','name_en' => 'Bangladesh','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '23','sevdesk_id' => '1445','code' => 'bb','name' => 'Barbados','name_en' => 'Barbados','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '24','sevdesk_id' => '6','code' => 'be','name' => 'Belgien','name_en' => 'Belgium','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '25','sevdesk_id' => '46','code' => 'bz','name' => 'Belize','name_en' => 'Belize','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '26','sevdesk_id' => '1437','code' => 'ben','name' => 'Benin','name_en' => 'Benin','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '27','sevdesk_id' => '1472','code' => 'bj','name' => 'Benin','name_en' => 'Benin','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '28','sevdesk_id' => '1476','code' => 'bm','name' => 'Bermuda','name_en' => 'Bermuda','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '29','sevdesk_id' => '1350','code' => 'bt','name' => 'Bhutan','name_en' => 'Bhutan','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '30','sevdesk_id' => '1477','code' => 'bo','name' => 'Bolivien','name_en' => 'Bolivia','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '31','sevdesk_id' => '53','code' => 'ba','name' => 'Bosnien','name_en' => 'Bosnia','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '32','sevdesk_id' => '1396','code' => 'ba','name' => 'Bosnien-Herzegowina','name_en' => 'Bosnien-Herzegowina','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '33','sevdesk_id' => '1481','code' => 'bw','name' => 'Botswana','name_en' => 'Botswana','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '34','sevdesk_id' => '1480','code' => 'bv','name' => 'Bouvetinsel','name_en' => 'Bouvet Island','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '35','sevdesk_id' => '73','code' => 'br','name' => 'Brasilien','name_en' => 'Brazil','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '36','sevdesk_id' => '1391','code' => 'vg','name' => 'Britische Jungferninseln','name_en' => 'Virgin Islands','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '37','sevdesk_id' => '1514','code' => 'io','name' => 'Britisches Territorium im Indischen Ozean','name_en' => 'British Indian Ocean Territory','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '38','sevdesk_id' => '1479','code' => 'bn','name' => 'Brunei','name_en' => 'Brunei','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '39','sevdesk_id' => '7','code' => 'bg','name' => 'Bulgarien','name_en' => 'Bulgaria','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '40','sevdesk_id' => '1473','code' => 'bf','name' => 'Burkina Faso','name_en' => 'Burkina Faso','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '41','sevdesk_id' => '1404','code' => 'bi','name' => 'Burundi','name_en' => 'Burundi','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '42','sevdesk_id' => '49','code' => 'cl','name' => 'Chile','name_en' => 'Chile','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '43','sevdesk_id' => '1486','code' => 'ck','name' => 'Cookinseln','name_en' => 'Cook Islands','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '44','sevdesk_id' => '1421','code' => 'cr','name' => 'Costa Rica','name_en' => 'Costa Rica','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '45','sevdesk_id' => '1455','code' => 'cw','name' => 'Curacao','name_en' => 'Curacao','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '46','sevdesk_id' => '8','code' => 'dk','name' => 'Dänemark','name_en' => 'Denmark','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '47','sevdesk_id' => '1','code' => 'de','name' => 'Deutschland','name_en' => 'Germany','offset' => '99','created_at' => NULL,'updated_at' => NULL),
            array('id' => '48','sevdesk_id' => '1491','code' => 'dm','name' => 'Dominica','name_en' => 'Dominica','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '49','sevdesk_id' => '1447','code' => 'do','name' => 'Dominikanische Republik','name_en' => 'Dominican Republic','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '50','sevdesk_id' => '1405','code' => 'dj','name' => 'Dschibuti','name_en' => 'Djibouti','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '51','sevdesk_id' => '67','code' => 'du','name' => 'Dubai','name_en' => 'Dubai','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '52','sevdesk_id' => '1492','code' => 'ec','name' => 'Ecuador','name_en' => 'Ecuador','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '53','sevdesk_id' => '1434','code' => 'EC','name' => 'Ekuador','name_en' => 'Ecuador','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '54','sevdesk_id' => '1450','code' => 'sv','name' => 'El Salvador','name_en' => 'El Salvador','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '55','sevdesk_id' => '1381','code' => 'ci','name' => 'Elfenbeinküste','name_en' => 'Ivory Coast','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '56','sevdesk_id' => '74','code' => 'england','name' => 'England','name_en' => 'England','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '57','sevdesk_id' => '1406','code' => 'er','name' => 'Eritrea','name_en' => 'Eritrea','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '58','sevdesk_id' => '72','code' => 'ee','name' => 'Estland','name_en' => 'Estonia','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '59','sevdesk_id' => '1390','code' => 'ee','name' => 'Estland','name_en' => 'Estonia','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '60','sevdesk_id' => '1495','code' => 'fk','name' => 'Falklandinseln','name_en' => 'Falkland Islands','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '61','sevdesk_id' => '1496','code' => 'fo','name' => 'Färöer-Inseln','name_en' => 'Faroe Islands','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '62','sevdesk_id' => '1494','code' => 'fj','name' => 'Fidschi','name_en' => 'Fiji','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '63','sevdesk_id' => '10','code' => 'fi','name' => 'Finnland','name_en' => 'Finland','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '64','sevdesk_id' => '11','code' => 'fr','name' => 'Frankreich','name_en' => 'France','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '65','sevdesk_id' => '1507','code' => 'gf','name' => 'Französisch Guyana','name_en' => 'French Guiana','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '66','sevdesk_id' => '1351','code' => 'pf','name' => 'Französisch-Polynesien','name_en' => 'French-Polynesia','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '67','sevdesk_id' => '1471','code' => 'tf','name' => 'Französische Süd-und Antarktisgebiete','name_en' => 'French Southern and Antarctic Lands','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '68','sevdesk_id' => '1498','code' => 'ga','name' => 'Gabun','name_en' => 'Gabon','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '69','sevdesk_id' => '1501','code' => 'gm','name' => 'Gambia','name_en' => 'Gambia','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '70','sevdesk_id' => '1394','code' => 'ge','name' => 'Georgien','name_en' => 'Georgia','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '71','sevdesk_id' => '1382','code' => 'gh','name' => 'Ghana','name_en' => 'Ghana','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '72','sevdesk_id' => '1377','code' => 'gib','name' => 'Gibraltar','name_en' => 'Gibraltar','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '73','sevdesk_id' => '1500','code' => 'gi','name' => 'Gibraltar','name_en' => 'Gibraltar','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '74','sevdesk_id' => '1402','code' => 'wg','name' => 'Grenada','name_en' => 'Grenada','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '75','sevdesk_id' => '1504','code' => 'gd','name' => 'Grenada','name_en' => 'Grenada','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '76','sevdesk_id' => '12','code' => 'gr','name' => 'Griechenland','name_en' => 'Greece','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '77','sevdesk_id' => '1505','code' => 'gl','name' => 'Grönland','name_en' => 'Greenland','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '78','sevdesk_id' => '9','code' => 'gb','name' => 'Großbritannien','name_en' => 'United Kingdom','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '79','sevdesk_id' => '1438','code' => 'gp','name' => 'Guadeloupe','name_en' => 'Guadeloupe','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '80','sevdesk_id' => '1508','code' => 'gu','name' => 'Guam','name_en' => 'Guam','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '81','sevdesk_id' => '1506','code' => 'gt','name' => 'Guatemala','name_en' => 'Guatemala','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '82','sevdesk_id' => '1499','code' => 'gg','name' => 'Guernsey','name_en' => 'Guernsey','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '83','sevdesk_id' => '1376','code' => 'gn','name' => 'Guinea','name_en' => 'Guinea','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '84','sevdesk_id' => '1502','code' => 'gw','name' => 'Guinea-Bissau','name_en' => 'Guinea-Bissau','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '85','sevdesk_id' => '1509','code' => 'gy','name' => 'Guyana','name_en' => 'Guyana','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '86','sevdesk_id' => '1512','code' => 'ht','name' => 'Haiti','name_en' => 'Haiti','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '87','sevdesk_id' => '1510','code' => 'hm','name' => 'Heard und die McDonaldinseln','name_en' => 'Heard Island and McDonald Islands','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '88','sevdesk_id' => '1511','code' => 'hn','name' => 'Honduras','name_en' => 'Honduras','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '89','sevdesk_id' => '59','code' => 'hk','name' => 'Hong Kong','name_en' => 'Hong Kong','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '90','sevdesk_id' => '62','code' => 'in','name' => 'India','name_en' => 'Indene','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '91','sevdesk_id' => '1375','code' => 'in','name' => 'Indien','name_en' => 'India','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '92','sevdesk_id' => '1374','code' => 'id','name' => 'Indonesien','name_en' => 'Indonesia','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '93','sevdesk_id' => '1513','code' => 'im','name' => 'Insel Man','name_en' => 'Isle of Man','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '94','sevdesk_id' => '1419','code' => 'iq','name' => 'Irak','name_en' => 'Iraq','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '95','sevdesk_id' => '1373','code' => 'ir','name' => 'Iran','name_en' => 'Iran','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '96','sevdesk_id' => '13','code' => 'ie','name' => 'Irland','name_en' => 'Ireland','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '97','sevdesk_id' => '51','code' => 'is','name' => 'Island','name_en' => 'Iceland','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '98','sevdesk_id' => '36','code' => 'il','name' => 'Israel','name_en' => 'Israel','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '99','sevdesk_id' => '14','code' => 'it','name' => 'Italien','name_en' => 'Italy','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '100','sevdesk_id' => '15','code' => 'jm','name' => 'Jamaika','name_en' => 'Jamaica','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '101','sevdesk_id' => '40','code' => 'jp','name' => 'Japan','name_en' => 'Japan','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '102','sevdesk_id' => '1459','code' => 'ye','name' => 'Jemen','name_en' => 'Yemen','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '103','sevdesk_id' => '1441','code' => 'jey','name' => 'Jersey','name_en' => 'Jersey','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '104','sevdesk_id' => '1515','code' => 'je','name' => 'Jersey','name_en' => 'Jersey','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '105','sevdesk_id' => '1344','code' => 'jo','name' => 'Jordanien','name_en' => 'Jordan','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '106','sevdesk_id' => '1460','code' => 'ky','name' => 'Kaimaninseln','name_en' => 'Cayman Islands','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '107','sevdesk_id' => '1401','code' => 'kh','name' => 'Kambodscha','name_en' => 'Cambodia','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '108','sevdesk_id' => '1400','code' => 'cm','name' => 'Kamerun','name_en' => 'Cameroon','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '109','sevdesk_id' => '39','code' => 'ca','name' => 'Kanada','name_en' => 'Canada','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '110','sevdesk_id' => '1423','code' => 'ca','name' => 'Kanada','name_en' => 'Canada','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '111','sevdesk_id' => '1487','code' => 'cv','name' => 'Kap Verde','name_en' => 'Cape Verde','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '112','sevdesk_id' => '1478','code' => 'bq','name' => 'Karibische Niederlande','name_en' => 'Caribbean Netherlands','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '113','sevdesk_id' => '56','code' => 'kz','name' => 'Kasachstan','name_en' => 'Kazakhstan','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '114','sevdesk_id' => '1371','code' => 'qa','name' => 'Katar','name_en' => 'Qatar','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '115','sevdesk_id' => '1389','code' => 'ke','name' => 'Kenia','name_en' => 'Kenya','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '116','sevdesk_id' => '1430','code' => 'kg','name' => 'Kirgisistan','name_en' => 'Kyrgyzstan','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '117','sevdesk_id' => '1516','code' => 'ki','name' => 'Kiribati','name_en' => 'Kiribati','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '118','sevdesk_id' => '1555','code' => 'um','name' => 'Kleinere Inselbesitzungen der Vereinigten Staaten','name_en' => 'United States Minor Outlying Islands','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '119','sevdesk_id' => '1483','code' => 'cc','name' => 'Kokosinseln','name_en' => 'Cocos (Keeling) Islands','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '120','sevdesk_id' => '1403','code' => 'co','name' => 'Kolumbien','name_en' => 'Colombia','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '121','sevdesk_id' => '1407','code' => 'km','name' => 'Komoren','name_en' => 'Comoros','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '122','sevdesk_id' => '1485','code' => 'cg','name' => 'Kongo','name_en' => 'Republic of the Congo','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '123','sevdesk_id' => '1484','code' => 'cd','name' => 'Kongo (Dem. Rep.)','name_en' => 'DR Congo','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '124','sevdesk_id' => '1397','code' => 'xk','name' => 'Kosovo','name_en' => 'Kosovo','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '125','sevdesk_id' => '1422','code' => 'xk','name' => 'Kosovo','name_en' => 'Kosovo','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '126','sevdesk_id' => '1517','code' => 'xk','name' => 'Kosovo','name_en' => 'Kosovo','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '127','sevdesk_id' => '48','code' => 'hr','name' => 'Kroatien','name_en' => 'Croatia','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '128','sevdesk_id' => '1488','code' => 'cu','name' => 'Kuba','name_en' => 'Cuba','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '129','sevdesk_id' => '1369','code' => 'kw','name' => 'Kuwait','name_en' => 'Kuwait','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '130','sevdesk_id' => '1518','code' => 'la','name' => 'Laos','name_en' => 'Laos','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '131','sevdesk_id' => '1520','code' => 'ls','name' => 'Lesotho','name_en' => 'Lesotho','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '132','sevdesk_id' => '16','code' => 'lv','name' => 'Lettland','name_en' => 'Latvia','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '133','sevdesk_id' => '1428','code' => 'lb','name' => 'Libanon','name_en' => 'Lebanon','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '134','sevdesk_id' => '1519','code' => 'lr','name' => 'Liberia','name_en' => 'Liberia','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '135','sevdesk_id' => '1454','code' => 'ly','name' => 'Libyen','name_en' => 'Lybia','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '136','sevdesk_id' => '42','code' => 'li','name' => 'Liechtenstein','name_en' => 'Liechtenstein','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '137','sevdesk_id' => '1346','code' => 'lt','name' => 'Litauen','name_en' => 'Lithuania','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '138','sevdesk_id' => '17','code' => 'lu','name' => 'Luxemburg','name_en' => 'Luxembourg','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '139','sevdesk_id' => '61','code' => 'mo','name' => 'Macao','name_en' => 'Macao','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '140','sevdesk_id' => '1395','code' => 'mg','name' => 'Madagaskar','name_en' => 'Madagaskar','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '141','sevdesk_id' => '1408','code' => 'mw','name' => 'Malawi','name_en' => 'Malawi','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '142','sevdesk_id' => '1387','code' => 'my','name' => 'Malaysia','name_en' => 'Malaysia','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '143','sevdesk_id' => '1435','code' => 'MV','name' => 'Malediven','name_en' => 'Malediven','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '144','sevdesk_id' => '1457','code' => 'MV','name' => 'Malediven','name_en' => 'Maldives','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '145','sevdesk_id' => '1522','code' => 'mv','name' => 'Malediven','name_en' => 'Maldives','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '146','sevdesk_id' => '1461','code' => 'ml','name' => 'Mali','name_en' => 'Mali','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '147','sevdesk_id' => '37','code' => 'mt','name' => 'Malta','name_en' => 'Malta','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '148','sevdesk_id' => '1365','code' => 'ma','name' => 'Marokko','name_en' => 'Morocco','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '149','sevdesk_id' => '1523','code' => 'mh','name' => 'Marshallinseln','name_en' => 'Marshall Islands','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '150','sevdesk_id' => '1385','code' => 'mq','name' => 'Martinique','name_en' => 'Martinique','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '151','sevdesk_id' => '1364','code' => 'mr','name' => 'Mauretanien','name_en' => 'Mauritania','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '152','sevdesk_id' => '1363','code' => 'ms','name' => 'Mauritius','name_en' => 'Mauritius','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '153','sevdesk_id' => '1525','code' => 'mu','name' => 'Mauritius','name_en' => 'Mauritius','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '154','sevdesk_id' => '1409','code' => 'yt','name' => 'Mayotte','name_en' => 'Mayotte','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '155','sevdesk_id' => '1367','code' => 'mk','name' => 'Mazedonien','name_en' => 'Macedonia','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '156','sevdesk_id' => '64','code' => 'mx','name' => 'Mexiko','name_en' => 'Mexico','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '157','sevdesk_id' => '1497','code' => 'fm','name' => 'Mikronesien','name_en' => 'Micronesia','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '158','sevdesk_id' => '1362','code' => 'md','name' => 'Moldawien','name_en' => 'Moldova','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '159','sevdesk_id' => '43','code' => 'mc','name' => 'Monaco','name_en' => 'Monaco','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '160','sevdesk_id' => '1360','code' => 'mn','name' => 'Mongolei','name_en' => 'Mongolia','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '161','sevdesk_id' => '1343','code' => 'me','name' => 'Montenegro','name_en' => 'Montenegro','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '162','sevdesk_id' => '1398','code' => 'moc','name' => 'Mosambik','name_en' => 'Mozambique','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '163','sevdesk_id' => '1410','code' => 'mz','name' => 'Mosambik','name_en' => 'Mozambique','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '164','sevdesk_id' => '1359','code' => 'mm','name' => 'Myanmar','name_en' => 'Myanmar','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '165','sevdesk_id' => '1429','code' => 'na','name' => 'Namibia','name_en' => 'Namibia','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '166','sevdesk_id' => '1531','code' => 'nr','name' => 'Nauru','name_en' => 'Nauru','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '167','sevdesk_id' => '1462','code' => 'np','name' => 'Nepal','name_en' => 'Nepal','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '168','sevdesk_id' => '1358','code' => 'fr','name' => 'Neukaledonien','name_en' => 'New Caledonia','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '169','sevdesk_id' => '1526','code' => 'nc','name' => 'Neukaledonien','name_en' => 'New Caledonia','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '170','sevdesk_id' => '50','code' => 'nz','name' => 'Neuseeland','name_en' => 'New Zealand','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '171','sevdesk_id' => '1433','code' => 'kn','name' => 'Nevis','name_en' => 'Nevis','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '172','sevdesk_id' => '1529','code' => 'ni','name' => 'Nicaragua','name_en' => 'Nicaragua','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '173','sevdesk_id' => '18','code' => 'nl','name' => 'Niederlande','name_en' => 'Netherlands','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '174','sevdesk_id' => '1527','code' => 'ne','name' => 'Niger','name_en' => 'Niger','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '175','sevdesk_id' => '32','code' => 'ng','name' => 'Nigeria','name_en' => 'Nigeria','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '176','sevdesk_id' => '1530','code' => 'nu','name' => 'Niue','name_en' => 'Niue','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '177','sevdesk_id' => '1453','code' => 'kp','name' => 'Nordkorea','name_en' => 'North Korea','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '178','sevdesk_id' => '1524','code' => 'mp','name' => 'Nördliche Marianen','name_en' => 'Northern Mariana Islands','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '179','sevdesk_id' => '1528','code' => 'nf','name' => 'Norfolkinsel','name_en' => 'Norfolk Island','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '180','sevdesk_id' => '19','code' => 'no','name' => 'Norwegen','name_en' => 'Norway','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '181','sevdesk_id' => '1357','code' => 'om','name' => 'Oman','name_en' => 'Oman','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '182','sevdesk_id' => '3','code' => 'at','name' => 'Österreich','name_en' => 'Austria','offset' => '98','created_at' => NULL,'updated_at' => NULL),
            array('id' => '183','sevdesk_id' => '55','code' => 'pk','name' => 'Pakistan','name_en' => 'Pakistan','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '184','sevdesk_id' => '1464','code' => 'ps','name' => 'Palästina','name_en' => 'State of Palestine','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '185','sevdesk_id' => '1533','code' => 'pw','name' => 'Palau','name_en' => 'Palau','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '186','sevdesk_id' => '1446','code' => 'pa','name' => 'Panama','name_en' => 'Panama','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '187','sevdesk_id' => '1456','code' => 'pa','name' => 'Panama','name_en' => 'Panama','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '188','sevdesk_id' => '1534','code' => 'pg','name' => 'Papua-Neuguinea','name_en' => 'Papua New Guinea','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '189','sevdesk_id' => '1393','code' => 'py','name' => 'Paraguay','name_en' => 'Paraguay','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '190','sevdesk_id' => '69','code' => 'pe','name' => 'Peru','name_en' => 'Peru','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '191','sevdesk_id' => '1392','code' => 'ph','name' => 'Philippinen','name_en' => 'Philippines','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '192','sevdesk_id' => '1532','code' => 'pn','name' => 'Pitcairn','name_en' => 'Pitcairn Islands','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '193','sevdesk_id' => '21','code' => 'pl','name' => 'Polen','name_en' => 'Poland','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '194','sevdesk_id' => '22','code' => 'pt','name' => 'Portugal','name_en' => 'Portugal','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '195','sevdesk_id' => '1436','code' => 'pr','name' => 'Puerto Rico','name_en' => 'Puerto Rico','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '196','sevdesk_id' => '1535','code' => 're','name' => 'Réunion','name_en' => 'Réunion','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '197','sevdesk_id' => '1411','code' => 'rw','name' => 'Ruanda','name_en' => 'Rwanda','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '198','sevdesk_id' => '23','code' => 'ro','name' => 'Rumänien','name_en' => 'Romania','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '199','sevdesk_id' => '24','code' => 'ru','name' => 'Russland','name_en' => 'Russia','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '200','sevdesk_id' => '1521','code' => 'mf','name' => 'Saint Martin','name_en' => 'Saint Martin','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '201','sevdesk_id' => '1557','code' => 'vc','name' => 'Saint Vincent und die Grenadinen','name_en' => 'Saint Vincent and the Grenadines','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '202','sevdesk_id' => '1474','code' => 'bl','name' => 'Saint-Barthélemy','name_en' => 'Saint Barthélemy','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '203','sevdesk_id' => '1540','code' => 'pm','name' => 'Saint-Pierre und Miquelon','name_en' => 'Saint Pierre and Miquelon','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '204','sevdesk_id' => '1539','code' => 'sb','name' => 'Salomonen','name_en' => 'Solomon Islands','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '205','sevdesk_id' => '1412','code' => 'zm','name' => 'Sambia','name_en' => 'Zambia','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '206','sevdesk_id' => '1562','code' => 'ws','name' => 'Samoa','name_en' => 'Samoa','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '207','sevdesk_id' => '1451','code' => 'sm','name' => 'San Marino','name_en' => 'San Marino','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '208','sevdesk_id' => '1541','code' => 'st','name' => 'São Tomé und Príncipe','name_en' => 'São Tomé and Príncipe','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '209','sevdesk_id' => '57','code' => 'sa','name' => 'Saudi Arabien','name_en' => 'Saudi Arabia','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '210','sevdesk_id' => '25','code' => 'se','name' => 'Schweden','name_en' => 'Sweden','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '211','sevdesk_id' => '2','code' => 'ch','name' => 'Schweiz','name_en' => 'Switzerland','offset' => '97','created_at' => NULL,'updated_at' => NULL),
            array('id' => '212','sevdesk_id' => '1439','code' => 'sn','name' => 'Senegal','name_en' => 'Senegal','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '213','sevdesk_id' => '1379','code' => 'rs','name' => 'Serbien','name_en' => 'Serbia','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '214','sevdesk_id' => '1425','code' => 'rs','name' => 'Serbien','name_en' => 'Serbia','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '215','sevdesk_id' => '1388','code' => 'sc','name' => 'Seychellen','name_en' => 'Seychellen','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '216','sevdesk_id' => '1378','code' => 'sl','name' => 'Sierra Leone','name_en' => 'Sierra Leone','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '217','sevdesk_id' => '1413','code' => 'zw','name' => 'Simbabwe','name_en' => 'Zimbabwe','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '218','sevdesk_id' => '75','code' => 'sg','name' => 'Singapur','name_en' => 'Singapore','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '219','sevdesk_id' => '1544','code' => 'sx','name' => 'Sint Maarten','name_en' => 'Sint Maarten','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '220','sevdesk_id' => '27','code' => 'sk','name' => 'Slowakei','name_en' => 'Slovakia','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '221','sevdesk_id' => '28','code' => 'si','name' => 'Slowenien','name_en' => 'Slovenia','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '222','sevdesk_id' => '1414','code' => 'so','name' => 'Somalia','name_en' => 'Somalia','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '223','sevdesk_id' => '29','code' => 'es','name' => 'Spanien','name_en' => 'Spain','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '224','sevdesk_id' => '1538','code' => 'sj','name' => 'Spitzbergen','name_en' => 'Svalbard and Jan Mayen','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '225','sevdesk_id' => '1356','code' => 'lk','name' => 'Sri Lanka','name_en' => 'Sri Lanka','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '226','sevdesk_id' => '1475','code' => 'sh','name' => 'St. Helena, Ascension und Tristan da Cunha','name_en' => 'Saint Helena, Ascension and Tristan da Cunha','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '227','sevdesk_id' => '1448','code' => 'lc','name' => 'St. Lucia','name_en' => 'Saint Lucia','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '228','sevdesk_id' => '47','code' => 'za','name' => 'Südafrika','name_en' => 'South Africa','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '229','sevdesk_id' => '1536','code' => 'sd','name' => 'Sudan','name_en' => 'Sudan','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '230','sevdesk_id' => '1537','code' => 'gs','name' => 'Südgeorgien und die Südlichen Sandwichinseln','name_en' => 'South Georgia','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '231','sevdesk_id' => '41','code' => 'kr','name' => 'Südkorea','name_en' => 'South Korea','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '232','sevdesk_id' => '1452','code' => 'kr','name' => 'Südkorea','name_en' => 'South Korea','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '233','sevdesk_id' => '1415','code' => 'ss','name' => 'Südsudan','name_en' => 'South Sudan','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '234','sevdesk_id' => '1542','code' => 'sr','name' => 'Suriname','name_en' => 'Suriname','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '235','sevdesk_id' => '1543','code' => 'sz','name' => 'Swasiland','name_en' => 'Swaziland','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '236','sevdesk_id' => '1545','code' => 'sy','name' => 'Syrien','name_en' => 'Syria','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '237','sevdesk_id' => '1431','code' => 'syr','name' => 'Syrien','name_en' => 'Syria','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '238','sevdesk_id' => '1548','code' => 'tj','name' => 'Tadschikistan','name_en' => 'Tajikistan','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '239','sevdesk_id' => '68','code' => 'tw','name' => 'Taiwan','name_en' => 'Taiwan','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '240','sevdesk_id' => '1424','code' => 'tw','name' => 'Taiwan','name_en' => 'Taiwan','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '241','sevdesk_id' => '1416','code' => 'tz','name' => 'Tansania','name_en' => 'Tanzania','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '242','sevdesk_id' => '1380','code' => 'th','name' => 'Thailand','name_en' => 'Thailand','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '243','sevdesk_id' => '1551','code' => 'tl','name' => 'Timor-Leste','name_en' => 'Timor-Leste','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '244','sevdesk_id' => '1463','code' => 'tg','name' => 'Togo','name_en' => 'Togo','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '245','sevdesk_id' => '1549','code' => 'tk','name' => 'Tokelau','name_en' => 'Tokelau','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '246','sevdesk_id' => '1552','code' => 'to','name' => 'Tonga','name_en' => 'Tonga','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '247','sevdesk_id' => '1553','code' => 'tt','name' => 'Trinidad und Tobago','name_en' => 'Trinidad and Tobago','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '248','sevdesk_id' => '1547','code' => 'td','name' => 'Tschad','name_en' => 'Chad','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '249','sevdesk_id' => '30','code' => 'cz','name' => 'Tschechien','name_en' => 'Czech Republic','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '250','sevdesk_id' => '1354','code' => 'tn','name' => 'Tunesien','name_en' => 'Tunisia','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '251','sevdesk_id' => '34','code' => 'tr','name' => 'Türkei','name_en' => 'Turkey','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '252','sevdesk_id' => '1550','code' => 'tm','name' => 'Turkmenistan','name_en' => 'Turkmenistan','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '253','sevdesk_id' => '1546','code' => 'tc','name' => 'Turks-und Caicosinseln','name_en' => 'Turks and Caicos Islands','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '254','sevdesk_id' => '1554','code' => 'tv','name' => 'Tuvalu','name_en' => 'Tuvalu','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '255','sevdesk_id' => '1417','code' => 'ug','name' => 'Uganda','name_en' => 'Uganda','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '256','sevdesk_id' => '66','code' => 'ua','name' => 'Ukraine','name_en' => 'Ukraine','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '257','sevdesk_id' => '1337','code' => 'unknown','name' => 'Unbekannt','name_en' => '','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '258','sevdesk_id' => '31','code' => 'hu','name' => 'Ungarn','name_en' => 'Hungary','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '259','sevdesk_id' => '1384','code' => 'uy','name' => 'Uruguay','name_en' => 'Uruguay','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '260','sevdesk_id' => '35','code' => 'us','name' => 'USA','name_en' => 'USA','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '261','sevdesk_id' => '1342','code' => 'uz','name' => 'Usbekistan','name_en' => 'Uzbekistan','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '262','sevdesk_id' => '1560','code' => 'vu','name' => 'Vanuatu','name_en' => 'Vanuatu','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '263','sevdesk_id' => '1556','code' => 'va','name' => 'Vatikanstadt','name_en' => 'Vatican City','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '264','sevdesk_id' => '1558','code' => 've','name' => 'Venezuela','name_en' => 'Venezuela','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '265','sevdesk_id' => '44','code' => 'ae','name' => 'Vereinigte Arabische Emirate','name_en' => 'United Arab Emirates','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '266','sevdesk_id' => '1353','code' => 'us','name' => 'Vereinigte Staaten','name_en' => 'The United States','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '267','sevdesk_id' => '1352','code' => 'vn','name' => 'Vietnam','name_en' => 'Vietnam','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '268','sevdesk_id' => '60','code' => 'cn','name' => 'Volksrepublik China','name_en' => 'People\'s Republic of China','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '269','sevdesk_id' => '45','code' => 'tw','name' => 'Volksrepublik China (Taiwan)','name_en' => 'People\'s Republic of China (Taiwan)','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '270','sevdesk_id' => '1561','code' => 'wf','name' => 'Wallis und Futuna','name_en' => 'Wallis and Futuna','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '271','sevdesk_id' => '1489','code' => 'cx','name' => 'Weihnachtsinsel','name_en' => 'Christmas Island','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '272','sevdesk_id' => '76','code' => 'by','name' => 'Weißrussland','name_en' => 'White Russia','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '273','sevdesk_id' => '1493','code' => 'eh','name' => 'Westsahara','name_en' => 'Western Sahara','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '274','sevdesk_id' => '1482','code' => 'cf','name' => 'Zentralafrikanische Republik','name_en' => 'Central African Republic','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '275','sevdesk_id' => '1386','code' => 'cyp','name' => 'Zypern','name_en' => 'Cyprus','offset' => '0','created_at' => NULL,'updated_at' => NULL),
            array('id' => '276','sevdesk_id' => '1490','code' => 'cy','name' => 'Zypern','name_en' => 'Cyprus','offset' => '0','created_at' => NULL,'updated_at' => NULL)
          )
      );
    }
}
